# Generated by Django 5.0.6 on 2024-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='category',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20, null=True),
        ),
    ]
