# Generated by Django 5.0.6 on 2024-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_topping_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='slices',
            field=models.PositiveIntegerField(max_length=2, null=True),
        ),
    ]
