# Generated by Django 5.0.6 on 2024-07-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_size_slices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='payment_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
