# Generated by Django 5.0.6 on 2024-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_customerorder_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='slices',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
