# Generated by Django 5.0.6 on 2024-07-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_customerorder_total_amount_alter_size_slices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='item_in_cart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
